---
- name: "Create {{app_user}} group"
  sudo: yes
  group: name={{app_user}} system=yes

- name: "Create {{app_user}} user"
  sudo: yes
  user: name={{app_user}} system=yes group=app shell=/usr/sbin/nologin home={{app_home}} createhome=yes

- name: "Installing app {{app.name}}" 
  appmgr_app: upgrade={{upgrade}} coordinates={{app_coordinates}} name={{app.name}} maven_repository={{maven_repository}} user={{app_user}} group={{app_group}} base={{app_home}}
  sudo: yes
  sudo_user: "{{app_user}}"
  notify:
    - "restart app {{app.name}}"

- name: "Configuring app {{app.name}}"
  appmgr_config: name={{app.name}} key={{item.name}} value={{item.value}}
  with_items: app.config
  sudo_user: "{{app_user}}"
  sudo: yes

- name: "Handling environment variables"
  template: src=environment.j2 dest=/opt/apps/{{app.name}}/environment
  sudo: yes

- name: "Install app :: Add monit scripts"
  template: src=monit/conf.d/app.j2 dest=/etc/monit/conf.d/{{app.name}} owner=root group=root mode=0700
  sudo: yes

- name: "Restart monit"
  service: name=monit state=restarted
  sudo: yes

- include: ec2.yml
